### ISSUE TITLE
Check if element in template exists before adding event listener

### ISSUE THREAD

**Issue by lagwagon** [kogmbh/ViewerJS#100]
Just ran into an issue after I edited the default template. Some people may want to remove (not just hide) the download button entirely, or make aesthetic changes to the default template.

None of the buttons (zoom functions namely) would work thanks to a js error when the script would try to add an event listener to an element you removed from the template.

**Comment by kossebau** [comment]
Hi, thanks for your request. Just, the "default template" is not meant as a template, but as the one and only shell. At least the current mission statement of ViewerJS is to be a simple to use component that people can use just by an url for an iframe or as whole page, with `"/ViewerJS/#path/to/document"`.
Support for further configuration/customization is not yet part of this mission, to stay focussed.
So your needs sadly cannot be matched these days by this project.
Thus closing this issue for now as invalid.
