### ISSUE TITLE
Documents from Amazon S3 is not getting displayed

### ISSUE THREAD

**Issue by pradheep91** [kogmbh/ViewerJS#101]
I have uploaded some same .pdf,.odt,.odp and .ods files in my Amazon S3 bucket and marked all the documents as public and copied the public url for the document and pasted in my code.The document is not getting viewed but when the download button is clicked the document is getting downloaded perfectly.When i try to open the same files from my local file system it is working perfectly.

Is this an issue or any suggestions to overcome this problem.

**Comment by macphoto** [comment]
Are there instructions for implementing ViewerJS with Amazon S3? I would like to syndicate PDF content from my S3 account using an iframe embed code. Any assistance would be greatly appreciated.

**Comment by RyanQuey** [comment]
I found combining the instructions for using an [external site](https://github.com/webodf/ViewerJS/issues/105#issuecomment-64792068) and for adding [query params](https://github.com/webodf/ViewerJS/issues/91#issuecomment-74167210) (ie for access tokens etc) worked to access s3 files

**Comment by macphoto** [comment]
Wow.... I posted my inquiry four years ago, and now there is a reply? Well, I've resolved my issue with the use of the security settings that are available within Google Drive. Google has provided a simple way to discourage or deflect site viewers from unauthorized downloads of documents. Yea... View but don't touch!
