### ISSUE TITLE
pdf file ask to download. but dont show in viewr. it is empty

### ISSUE THREAD

**Issue by tkurulla** [kogmbh/ViewerJS#107]
pdf file ask to download but viewr shows empty. how to fix it?

**Comment by a-lucas** [comment]
Same problem here. 

The pdf is accessed via Zend 's action which generate a pdf file on the fly with readfile().
it is accessible from /getDocument/123

when I go : http://mydomain.com/getDocument/123, I download a PDF file.

But when I try : 

     http://mydomain.com/js/lib/ViewerJS/#../../../getDocument/123

I got an empty page.

**Comment by kossebau** [comment]
Duplicate of #27, thus closing now.
Please see that issue also to learn about it being dealt with in today's release of ViewerJS 0.5.5.
