### ISSUE TITLE
cannot view odt file properly

### ISSUE THREAD

**Issue by SuYeeHlaing** [kogmbh/ViewerJS#109]
Hi,
![untitled](https://cloud.githubusercontent.com/assets/10085229/5334542/27ede84c-7ece-11e4-8407-6fa886c018ed.png)

I can't view odt files and others except pdf and ods files. I got that message when I clicked ViewerJS.....and also I want to see the MS office document with viwerjs.....Please help me.

Moreover, In web browser console, I got the following message....
"WARNING: refreshOdf called but ODF was not DONE."
"will be back later..."

Thank you...

**Comment by kossebau** [comment]
Good that you could solve it :) So closing this issue now.
(If you like and would like to help others who might have run into the same problem, you still can describe in another comment what the reason was and how you solved it)

**Comment by vrdakoju22** [comment]
> I solved it. Thank you.

Could you please let me know, how did you solved?
Thanks
