### ISSUE TITLE
How to show .html in Viewer

### ISSUE THREAD

**Issue by jai2shukla** [kogmbh/ViewerJS#110]
Gone through the ViewerJS and it says that we can show .html file but not able to show. I downloaded the file but it has implemented only 2 types of file i.e. pdf and ots. Can you please tell me how to show .html file in ViewerJS?. Is there any specific plugin required to show .html file in ViewerJS. If yes then please provide us so that we can implement it.

**Comment by kossebau** [comment]
Closing, as this seems a strange request without the required info given to handle it.
