### ISSUE TITLE
getting Page Index 0 not found in Mozilla

### ISSUE THREAD

**Issue by anuragbit03** [kogmbh/ViewerJS#113]
Hi,
While opening PDF, viewer is appearing blank in Mozilla where as I am able to open same PDF in chrome. Please suggest me , how can I open pdf in Mozilla.

**Comment by kossebau** [comment]
Hi. Which version of "Mozilla"? And do you mean Firefox?
In general it should work the same in Firefox, Chrome and any other modern browser. Can you paste the content of the (Web) Console in Firefox (reachable by Ctrl-Shift-K usually)?

**Comment by kossebau** [comment]
Ping? Without the requested info we will have to close this issue as there is nothing we can do otherwise to help or find a bug. Closing March 31, if there is no reply from you.

**Comment by kossebau** [comment]
Closing due to no further info provided.
