### ISSUE TITLE
add bower

### ISSUE THREAD

**Issue by Angularjschile** [kogmbh/ViewerJS#114]
register in bower please

**Comment by kossebau** [comment]
Hi, thanks for the reminder :) We have setup a bower package for ViewerJS at https://github.com/kogmbh/ViewerJS_release. Registering as "viewerjs" at the central Bower registry so far was blocked by somebody else having once done a ViewerJS package and registering it with that name. We tried to contact that person in the last two months, but without success.
So just now finally have officially asked for re-registering, see
https://github.com/bower/bower/issues/120#issuecomment-69328333

Please try github.com/kogmbh/ViewerJS_release already and give some feedback if it also works for you and what could be improved.

**Comment by kossebau** [comment]
ViewerJS is now officially registered in the central registry, see http://bower.io/search/?q=viewerjs
Thus closing this issue now.
Still looking for more feedback if everything works as expected with that package, so if you have some time, please tell us :)
