### ISSUE TITLE
Your pdf example doesn't work

### ISSUE THREAD

**Issue by courtaks** [kogmbh/ViewerJS#118]

**Comment by kossebau** [comment]
Hi. Thanks for the feedback, but it misses lots of info to be usable :)
Which pdf example exactly? With which browser? And which version of ViewerJS?

**Comment by kossebau** [comment]
Ping? Without the requested info we will have to close this issue as there is nothing we can do otherwise to help or find a bug. Closing March 31, if there is no reply from you.
