### ISSUE TITLE
Excel and Docx not showing in the viewer

### ISSUE THREAD

**Issue by GuruMidhin** [kogmbh/ViewerJS#120]
I converted it to open source document.Still not showing in the viewer,it is getting downloaded

**Comment by kossebau** [comment]
Hi. To be able to help you we need more information.
How are you trying to use ViewerJS? What url are you using as src for the iframe? Does it work for files which are originally in PDF or one of the ODF formats? Try e.g. with the example files on viewerjs.org by downloading them and putting on your server
Are the files you are using public? So could you make them available by a link, so we could test with the files?

**Comment by kossebau** [comment]
Ping? Without the requested info we will have to close this issue as there is nothing we can do otherwise to help or find a bug. Closing March 31, if there is no reply from you.

**Comment by kossebau** [comment]
Closing due to no further info provided.
