### ISSUE TITLE
Is it possible to open a pdf/odf on a set page?

### ISSUE THREAD

**Issue by martsky-mart** [kogmbh/ViewerJS#121]
Ideally we need to open documents in viewerJS on a set page, in the way that pdf.js allows  #page= to be passsed. Is this possible?

**Comment by kossebau** [comment]
It is not yet possible up to current v0.5.5, but planned for one of the upcoming releases in the next months.

**Comment by kossebau** [comment]
The latest ViewerJS version 0.5.6 of today allows to control the starting page by a parameter `startpage`, e.g. like this:
```
ViewerJS/?startpage=14#../document.pdf
```
Not yet documented on viewerjs.org, but soon will. (Works with PDF & ODP. Does not work with ODT though, given that WebODF still renders that unpaged).
