### ISSUE TITLE
Images don't work

### ISSUE THREAD

**Issue by chrishall9521** [kogmbh/ViewerJS#123]
Trying to preview a jpeg, png, and other image types in here dose not work. Is there a work around or can this be fixed??

**Comment by kossebau** [comment]
Hi. First a curious question as feedback for us: what made you think ViewerJS supports images? The name? Or is this claimed somewhere?

The answer to your question is that currently ViewerJS does not (yet) support images. Somebody started a plugin for it, but it has not yet reached a state where it is bug-free enough to be integrated: #28. So yes, there is a work around and it can be fixed, e.g. by completing that plugin.
Needs someone to invest into  it, either time or money :)

**Comment by chrishall9521** [comment]
Hi, Thank you for responding!
It was just an assumption that if the application could support documents such as pdf's etc. that it would also support images as well.
The name does slightly imply that it could do this. But it isn't stated anywhere.
Would love to have the plugin eventually but isn't a priority at the moment. 
Great product!
The only thing that I would change is the positioning of the zoom buttons (+/-). It looks like they switch between pages.
And the image thing of course :)
Thanks for replying and keep me informed about this possible plugin!
Regards

Date: Thu, 19 Feb 2015 04:54:32 -0800

**Comment by kossebau** [comment]
Closing this issue as resolved and duplicate, supporting images is (indirectly) tracked by #28.
