### ISSUE TITLE
Header and footer of odt document missing 

### ISSUE THREAD

**Issue by dheerajkumar123** [kogmbh/ViewerJS#124]
header and footer do not show up when viewed in viewerJs

**Comment by kossebau** [comment]
Thanks for the report. This is a known issue to the developers of WebODF, which is used by ViewerJS for ODT documents.
I now filed this explicitely as issue with them: https://github.com/kogmbh/WebODF/issues/873
Please track that issue over there if you are interested to learn about how things develop.
Closing the issue for ViewerJS, as there is nothing in ViewerJS to be done about that.
