### ISSUE TITLE
Get a grey screen while the full pdf is downloaded before display

### ISSUE THREAD

**Issue by Shreeshrii** [kogmbh/ViewerJS#127]
I am testing ViewerJS as a way to display large pdf files with navigation in webpages. The files are large, soem are multiple MB in size. eg. http://sanskritdocuments.org/ViewerJS/#..doc_z_otherlang_hindi/manas5_i.pdf

The page displays with a gray background - no progress bar or any indication that file is loading - 
![image](https://cloud.githubusercontent.com/assets/5095331/6795149/f8166f86-d201-11e4-93d9-00e731838154.png)

Is there any option that can be set for displaying first page after it has been downloaded, rather than waiting for whole file to download.

edit: Even after waiting for a long while, the pdf is not displaying.

**Comment by kossebau** [comment]
Yes, not displaying, because there is a typo in the url: "/" missing after ".." :)
This works for me http://sanskritdocuments.org/ViewerJS/#../doc_z_otherlang_hindi/manas5_i.pdf

But still a loading indicator is missing, right. Tracked as #96

**Comment by vhugogarcia** [comment]
As a temporary solution for the loading, nit fancy, but to just let the user that the file is loading I did this:

on index.html file
Find: <div id = "canvas"></div>
Replace with: <div id="canvasLoading">Loading...</div>
                <div id = "canvas"></div>

on PDFViewerPlugin.js file
Find: completeLoading();
Replace with: completeLoading(); document.getElementById("canvasLoading").style.display = 'none';  

Hope this helps!

Thanks

**Comment by deepak-zyxware** [comment]
I have did a workaround as following, as I couldn't find the method **completeLoading();**

On index.html

> Find: <div id = "canvas"></div>
> Replace with: <div id="canvasLoading">Loading...</div>
>                 <div id = "canvas"></div>

On PDFViewerPlugin.js

> Find: for (i = 0; i < pdfDocument.numPages; i += 1) {
>                      pdfDocument.getPage(i + 1).then(createPage);
>                  }
> 
>                  initialized = true;
>              });
> 
>  Replace:  for (i = 0; i < pdfDocument.numPages; i += 1) {
>                      pdfDocument.getPage(i + 1).then(createPage);
>                  }
> 
>                  document.getElementById("canvasLoading").style.display = 'none';
>                  initialized = true;
>              });
