### ISSUE TITLE
Auto Preview

### ISSUE THREAD

**Issue by sureshopensoft** [kogmbh/ViewerJS#128]
Hi,
Any options there to make auto preview in final output?
Thanks for Advance.

**Comment by kossebau** [comment]
Please help to help you and give some more details what you mean by "auto preview in final output", I am lost what you mean exactly.

**Comment by sureshopensoft** [comment]
Hi,
    I thank you for your kind response. 

In current view of viewer.js is like  this 
![current view](https://cloud.githubusercontent.com/assets/11133517/6818443/ba57c9ea-d2d5-11e4-9308-7117fe9dee69.JPG)

But I excepting no need to click user preview  link to view a pdf file. Is there any option to set automatically preview the pdf file on load  of page itself ?.

**Comment by kossebau** [comment]
I guess you are mixing up ViewerJS and some other project that has a file viewer.js (perhaps the one from DropBox?). At least the screenshot you made of viewer.js is nothing that looks like this ViewerJS (see viewerjs.org what this is about).

So if an embedded display of PDF is what you want, download ViewerJS from ViewerJS, follow the http://viewerjs.org/instructions/ to set it up and try it.

**Comment by kossebau** [comment]
Closing as invalid.
