### ISSUE TITLE
Viewer JS support image?

### ISSUE THREAD

**Issue by sureshopensoft** [kogmbh/ViewerJS#130]
Hi,
   I tried to open jpg and png files using viewer js but it cant open. Will viewer js  support images?

**Comment by kossebau** [comment]
Currently ViewerJS does not (yet) support images. Somebody started a plugin for it, but it has not yet reached a state where it is bug-free enough to be integrated: #28. So yes, one day ViewerJS will support images. But it needs someone to invest into it, either time or money :)

Closing this issue as resolved and duplicate, supporting images is (indirectly) tracked by #28.

**Comment by sureshopensoft** [comment]
Hi,
    Thanks for your kind response...
