### ISSUE TITLE
Bad Showing ods file

### ISSUE THREAD

**Issue by AndrewMot** [kogmbh/ViewerJS#135]
Hi

Thanks for this great tool.
I am trying to display correctly a ODS file but when I open it with ViewerJS, it appears like within an A4 or letter paper size.
The xls was converted to ods with unoconv python lib.
![1](https://cloud.githubusercontent.com/assets/11915875/7107950/1f6534e8-e13c-11e4-9619-cd891d2ff423.PNG)
![2](https://cloud.githubusercontent.com/assets/11915875/7108036/543099f8-e13f-11e4-9df4-680610547ef8.PNG)

 
I attach the image of how it shows in the viewer and how it shows in libreoffice

**Comment by kossebau** [comment]
Yes, sadly what you see reflects the current state of ViewerJS abilities with ODS.

We are looking forward to someone working on proper ODS display support (or investing into it), noone has worked since quite some time on that and currently noone is known to plan so :(

**Comment by AndrewMot** [comment]
Ok, bad news...
So, in my requirement maybe I only need adjust the page or paper size.
How can I do that?

**Comment by kossebau** [comment]
From what I remember about the code actually there is no concept about page or paper size with ODS, the code handles spreadsheets as something that has width and height as needed fo the cells. That there is a page border drawn though makes things confusing, agreed.

If in the zoom control of ViewerJS you select "100%", you should see that the size used is something random, calculated by the browser to fill in the cells of the table.
Just it seems that the browser tries hard to make the cells as small as possible, resulting in that bad display.
Possibly during the calculation of the CSS for the cells from the ODS styles some styling values about the cell sizes are not taking into account. But only guessing, no time to investigate.

ODS support really needs someone to give it some love, current support seems really only minimal at most :(

**Comment by AndrewMot** [comment]
Ohhh...nice play there.
Ok, yes I could see that. I'll see the code behind webodf.js to see If I can get some good results, If I can I'll report it here, whilst, I think It's opportune close this issue. 

I know, if someone is going to do it, he will do it with all concern to get the better product.

Thanks for your atention and help. Your work is appreciated.

**Comment by chenks** [comment]
> Yes, sadly what you see reflects the current state of ViewerJS abilities with ODS.
> 
> We are looking forward to someone working on proper ODS display support (or investing into it), noone has worked since quite some time on that and currently noone is known to plan so :(

sorry to comment on something from 2015, but i came across ViewerJS just yesterday when trying to find a solution to displaying spreadsheets within our website, whilst opening and viewing ODS spreadsheets "works", there are some weird display issues, where some fields return as blank even though they aren't in the ODS file itself.

did you come across a better solution to this?
this is my issue https://github.com/webodf/ViewerJS/issues/308
