### ISSUE TITLE
Automatic conversion of documents to open office or pdf

### ISSUE THREAD

**Issue by nodera1** [kogmbh/ViewerJS#138]
Is there a way automatically do document conversion to the accepted file types?

**Comment by kossebau** [comment]
Nothing which is built into ViewerJS.

A solution can be to convert the documents on-the-fly on a server, using e.g. LibreOffice in headless-mode or the Calligra converter. So the url passed to ViewerJS would request the converted file from that server, which would then create it as needed.

See https://github.com/owncloud/format-filter-server for some sample implementation.
