### ISSUE TITLE
Print button throws a JS error

### ISSUE THREAD

**Issue by mikeblum** [kogmbh/ViewerJS#141]
In our installation of Viewer.js, clicking on the print button throws an error. Here's a screenshot:

The print icon in Viewer.js throws a couple of javascript errors rather than printing:

![image](https://cloud.githubusercontent.com/assets/1377228/7397253/c1aeae18-ee6c-11e4-8e2a-48f93e1532d3.png)

![image](https://cloud.githubusercontent.com/assets/1377228/7397268/d66e8332-ee6c-11e4-82e4-d65c8f763cfe.png)

and for reference:

https://github.com/tsgrp/hpi/issues/665

**Comment by kossebau** [comment]
Hi. This looks like the "viewer.js" file from the pdf.js project.
This is the ViewerJS project, which also uses pdf.js for displaying PDFs. But we do not support printing :)
I guess you want to file this bug with pdf.js, if it really is an upstream problem.
Closing this issue for ViewerJS, as this is nothing about our code :)

**Comment by mikeblum** [comment]
Sorry, you're right, I updated the pdfJS build to the latest and the issue is resolved. Thanks for the quick reply.
