### ISSUE TITLE
ms word, excel, and ppt files

### ISSUE THREAD

**Issue by joomlaA1** [kogmbh/ViewerJS#178]
hello...

i have a compose message where users can upload files(as attachments)

then i have a view message where they can view the message(and the attachments as a list)

when i click an attachment on the list for viewing, i would like to use ViewerJS

but attachments could be a word doc, an excel file, or a ppt, among other files...

please help me how can i get through this....? i would like to use ViewerJS as the  viewer...

please help me view word excel ppt on viewerJS... thanks!

thanks @adityab @kossebau  @thz  @vandenoever 

i like the idea of no need to upload to internet

**Comment by joomlaA1** [comment]
hello thanks @adityab @kossebau @thz @vandenoever

**Comment by joomlaA1** [comment]
hi @adityab @kossebau  @thz  @vandenoever

**Comment by adityab** [comment]
Hi, right now, for documents, ViewerJS only supports ODF and PDF files. Sorry.

**Comment by joomlaA1** [comment]
thanks
