### ISSUE TITLE
Not getting scrollbars for a multiple page document. 

### ISSUE THREAD

**Issue by Babsobar** [kogmbh/ViewerJS#191]
Hello,
First of all, thank you for this plugin, it looks good.

I just finished installing it, everything works fine in loading the pdf, and displyaing it, but I'm not getting the possibility to scroll using the mousewheel, only the abilty to jump from page to page with the arrow keys. The lateral scrollbar isn't showing up either.

Edit:
Right, so after a bit of research, apparently I'm getting no scrollbar because my pdf is landscape, it's seen as a slideshow by viewerjs. I found a fix on another issue, but the mentioned file to change is not present in the last version of viewerjs.

What should I do to make sure it shows?

Thanks.
Babsobar

**Comment by Babsobar** [comment]
Never mind, I found it.
You now have to change a line of code, at ithe second occurence of this.isSlideshow in the index.html in index.html of viewer.js.

Solved using [this issue](https://github.com/kogmbh/ViewerJS/issues/111#issuecomment-82972471l)

It would be nice to have documentation on this, as that would save a lot of people a lot of time.

**Comment by MID904** [comment]
Hi, Babsobar I am sorry for reopening a closed issue, but would you please show me what changes you made in the mentioned line?

**Comment by MID904** [comment]
> Never mind, I found it.
> You now have to change a line of code, at ithe second occurence of this.isSlideshow in the index.html in index.html of viewer.js.
> 
> Solved using [this issue](https://github.com/kogmbh/ViewerJS/issues/111#issuecomment-82972471l)
> 
> It would be nice to have documentation on this, as that would save a lot of people a lot of time.

Hi, Babsobar I am sorry for reopening a closed issue, but would you please show me what changes you made in the mentioned line?
