### ISSUE TITLE
403 - Forbidden: Access is denied.

### ISSUE THREAD

**Issue by pr51713** [kogmbh/ViewerJS#193]
I was working on my computer and had no problem. I deploy it to production and the iframe shows 403:

<iframe src = "/Scripts/ViewerJS/#../../PDF/Test.pdf" width="500px" height="600px" allowfullscreen webkitallowfullscreen></iframe>

**Comment by leenaars** [comment]
A 403 code from the webserver means that the server is working but is not able to share the resource you are asking for. Typically, this happens when the files have the wrong UNIX access rights ... 

So this problem is not related to viewerJS.

**Comment by pr51713** [comment]
I have this running on IIS. Would you know how to give access to the PDF because I got the Iuser_IIS set for permissions on it.

**Comment by leenaars** [comment]
Sorry, have never worked with that. Generic answer: check the rights on files/folders that you *can* access, and make sure these are identical for the viewerJS files.

Some info specific to IIS 403 codes here: https://support.microsoft.com/en-us/kb/943891

**Comment by leenaars** [comment]
Just to be sure: it would seem to be not the PDF that has the rights problem, but the folder with viewerJS ...

**Comment by pr51713** [comment]
It if helps, I find my IIS uses IUSR. I gave IUSR Full access on both folders...the ViewerJS and the folder that has my PDF. Still no luck.

I then went to both those folders and enabled "Directory Browsing". It did not throw the error, but in the iframe, it only shows the directory of the ViewerJS. If I click on the index file, it looks like the code work in that if it knew a PDF, it should display it.

I'll dig more, but open to more suggestion if anyone knows more.

**Comment by leenaars** [comment]
Must be some IIS specific thing with directories then. 

In that case you can at least make it work by using the following incantation:

/viewerJS/index.html#../path/to/PDF.pdf

**Comment by pr51713** [comment]
BINGO!!! I guess I do not have "index.html" as a default file to fun. So when it looked for /viewerJS/#, the only file IIS kicks in to run is default.aspx. Not in that folder so it does nothing. Solution is either add index.html as a default file to use or specifically put in the index.html like you said above. Thank you!!
