### ISSUE TITLE
Which license does ViewerJS intend to ship with?

### ISSUE THREAD

**Issue by colmbrady** [kogmbh/ViewerJS#203]
I'm confused, maybe someone can help:

* the WebOdf component you use has a modified APGL license: http://webodf.org/about/license.html
* The PDF.js library is Apache2

In VewierJS, you include an APGL license also, which is an unmodified version.

So does this mean that ViewerJS essentially is APGL straight up?

Were you intending it to be the modified version of the APGL, but this just got missed by devs?

This comit seems to be when license got removed from ViewerJS: https://github.com/kogmbh/ViewerJS/commit/c489dc706a58ca8cd429dbd14bb8611a46742ede

**Comment by thz** [comment]
back then we had decided to put the code under the regular unmodified AGPL and add the exception to "binary" releases only.
so: yes, ViewerJS is under AGPL.
