### ISSUE TITLE
File loading in ViewerJS works sometimes, sometimes not

### ISSUE THREAD

**Issue by hjohanns** [kogmbh/ViewerJS#209]
Hello,
I have an issue with ViewerJS embedded into Tiki. On same OS (Windows), same Browser (Firefox), it is not working for employee, and working for me. It seems that the employee's browser performs only a direct file loading, whereas my browser performs a HEAD XHR tiki-download_file.php, then a load of pdf.js and others, then a GET XHR tiki-download_file.php
See line 337 of attached file.
Would like to understand how to investigate the issue.
Thanks a lot hj

[cleanWin-Firefox-viewerJS-load.txt](https://github.com/kogmbh/ViewerJS/files/310073/cleanWin-Firefox-viewerJS-load.txt)

**Comment by hjohanns** [comment]
I solved issues by 
- compiling and installing the latest ViewerJS
- looking carefully at the URL used, and replacing URL with
<path to ViewerJS>#http://a.b.c.d/<path to pdf> 
with a
<path to ViewerJS>#/<path to pdf> 
With the local file specification, it worked. My suspect is that the other browser had some more stringent settings for security.
It was painful that nobody could help or provide advice, but I hope this note can help someone else.
Best regards, hj

**Comment by euclife** [comment]
In my case, using firefox is not rendering.. just blank with iframe..
