### ISSUE TITLE
Does ViewerJS works with blob, stream or base64? 

### ISSUE THREAD

**Issue by AlexandreLPentila** [kogmbh/ViewerJS#216]
Hi, 

I'm trying to use your Viewer to display some PDF for all platform (Computer & mobile), which works great when I try to directly display a file. 

But when I try with my global stack (UI with JS on liferay back end) I got some trouble. 
In fact, my liferay is based on tomcat and I use struts action to get file. 
A call to struts action looks like : 

- https://My_URL/c/document_library/get_file?p_l_id=4179750&fileEntryId=4335401

When I directly try to call ViewerJS with the following call : 
- https://My_URL/ViewerJS#../c/document_library/get_file?p_l_id=4179750&fileEntryId=4335401
As I expect it doesn't works. 
I try to build a Blob object and call It in URL without success.

I also tried base 64 like describe in #6 with a request like : https://My_URL/ViewerJS/#data:application/pdf;base64,JVBERi0xLjY.................
I try it on chrome and firefox

Is it a mistake from myself?
Is it a known issue? 
Do you have some work around? 

Thanks a lot for any help!

Regards

**Comment by vandenoever** [comment]
Please check in the network tab of 'Inspect Element' to see there is a call to the pdf file.

**Comment by AlexandreLPentila** [comment]
@vandenoever  thanks for answer

**For the base 64 try :** 
Firstly I do a Jquery.GET on my URL which return the file content I convert in base64. 
Then, I just have to write the Base 64 at the end of the URL (which can be huge). 

In network : I can see my GET on URL and file content in response.

**For the "Jquery file" try :** 
When I Call the URL : 
https://My_URL/ViewerJS#../c/document_library/get_file?p_l_id=4179750&fileEntryId=4335401

I see in network the following call :
https://My_URL/c/document_library/get_file?p_l_id=4179750&fileEntryId=4335401 with HEAD request method which have nothing in response. But there is no GET call.

**For the "Direct file" try :** 
I got a HEAD request without response and a GET resquest with file in response. And it's works.

If you need more elements, ask them ;). 
Once again thanks for support.

**Comment by vandenoever** [comment]
Using the direct file method is simplest and most efficient. You say the direct file try works. Is there a reason that you cannot use that? If that does not work with the get_file URI, then you may have to escape the '&' and '=' symbols. What network traffic do you see when you try
  https://My_URL/ViewerJS#../c/document_library/get_file?p_l_id=4179750&fileEntryId=4335401
?

**Comment by AlexandreLPentila** [comment]
I know it's the simplest I can't in production. I just use It to test ViewerJS. 
I need to call the method getFiles which verify user permission some stuff like that.
My direct access is on the same serve but just try to access to a file I manually add to my /var/www directory

You can see the network calls : [http://hpics.li/a6c4e80](url)
There is redirection from "Viewer#../myCall" to "ViewerJS/#../myCall" but this redirection also exists when i try to access directly ("Viewer#../myFilePath").

If you need more details for some request I can post more details

**Comment by AlexandreLPentila** [comment]
Hi ,

Didn't solve the issue but I tried PDF.js and it work as expected, then I will use it.

Thanks for help.

**Comment by memorx** [comment]
Hi, can you share how do you solve your issue using PDF.js? thank you

**Comment by zenzei** [comment]
Hi @AlexandreLPentila, can you share how you resolved this issue? I'm having the same problem when streaming a file instead of static file.
Thanks,

**Comment by navinagarwal11** [comment]
Hi @AlexandreLPentila Please share how you have fixed the issue I am also facing same issue in Liferay 7.2

**Comment by jdiazgon55** [comment]
This works for me

`<iframe src="ViewerJS/#data:application/pdf;base64,JVBER....." >`
