### ISSUE TITLE
Dynamically generated PDF don't work

### ISSUE THREAD

**Issue by mattiz** [kogmbh/ViewerJS#27]
I have a service generating PDF's on the fly and returning it with the correct Content-Type and Content-disposition, but the viewer won't show it. If I save the PDF as a file, the viewer works as expected.

This doesn't work:
http://mypage.com/viewer.js/#http://mypage.com/service/createpdf

This works:
http://mypage.com/viewer.js/#http://mypage.com/file.pdf

**Comment by kossebau** [comment]
ViewerJS 0.5.5 got released today, and it improves situation around content type detection. It both tries to query to server for the mimetype initially and also can be passed the type as argument in the passed url, e.g. `/ViewerJS/index.html?type=pdf#http://mypage.com/service/createpdf`

That should solve this problem, so closing this issue.

**Comment by fukit0** [comment]
> ViewerJS 0.5.5 got released today, and it improves situation around content type detection. It both tries to query to server for the mimetype initially and also can be passed the type as argument in the passed url, e.g. `/ViewerJS/index.html?type=pdf#http://mypage.com/service/createpdf`
> 
> That should solve this problem, so closing this issue.

?type parameter is never mentioned in official site. I was struggling to view a pdf from blob url. That parameter made my day! Huge thanks!!!
