### ISSUE TITLE
Changing default buttons

### ISSUE THREAD

**Issue by Tentpig** [kogmbh/ViewerJS#29]
I would like to disable the presentation button, as it is currently not functional in IE 10. Is there a querystring option, without editing the source, to have this button not display, e.g. viewer.js/index.html?nopresentationbutton=1&.... ?

Also, when users click on the download button, the product does not download but instead opens the pdf in the same window with adobe reader, as most users have adobe reader installed. As such, is there a way to specify the target of the download button to be _blank rather than _self, so the adobe reader will open in a new window? Thanks much.

**Comment by kossebau** [comment]
In recent versions of ViewerJS the presentation button (and also the fullscreen button) should be no longer shown on browsers which do not support go.fullscreen calls, thus also IE10.
Please reopen if it still does for you, did not do for me with the latest version as also used on viewerjs.org.

The second issue will be tracked in #33
