### ISSUE TITLE
HTTP Error 404.0 - Not Found error when using it with asp.net webform

### ISSUE THREAD

**Issue by KamranShahid** [kogmbh/ViewerJS#36]
Hi guys,
I have tested the application using viewer.js with Visual studio internal web server (IIS Express) and it is working fine.If for instance I try to browse http://localhost:9069/Viewer.JS/index.html/#  it works fine
But when i published the application on IIS i am getting 404 error at the address 
http://publishedsite/Viewer.JS/index.html/#

it works fine if it is like http://publishedsite/Viewer.JS/index.html but it is of no use as i have to concatenate the url of my pdf file like
http://publishedsite/Viewer.JS/index.html/#http://publishedsite/mytest.pdf

Any particular settings required on IIS?

**Comment by kossebau** [comment]
If the given url `http://publishedsite/Viewer.JS/index.html/#`was not a typo, then the reply by th should have fixed things for you, as the `/` after `index.html` indeed should not be there.
Please consider telling us if that reply helped you or not, so we learn what the problems are.

Closing this issue now given a correct reply. Please reopen if your problem still exists.
