### ISSUE TITLE
Buttons stay highlighted/focussed after clicking on them

### ISSUE THREAD

**Issue by kossebau** [kogmbh/ViewerJS#38]
Focus seems to stay on toolbar elements when using them.

E.g. after having clicked the Previous Page button the button keeps the click-highlighting markup:
![focusstaysonbuttoninviewerjs](https://cloud.githubusercontent.com/assets/4068037/2550160/133ab072-b680-11e3-89b6-1432f5a9c797.png)

**Comment by kossebau** [comment]
Fixed in v0.5.6

**Comment by vgianni80** [comment]
Not work, i use in a .tpl file on Prestashop, and i can see only first page.
If i use this sintax:
   <iframe src = "/presta/ViewerJS/#..{$link->getPageLink('attachment',
true, NULL,
"id_attachment={$attachment.id_attachment}")|escape:'html':'UTF-8'}"
width='724' height='1024' allowfullscreen webkitallowfullscreen></iframe>
i can see only first page.

I tryed this sintax:
   <iframe src =
"/presta/ViewerJS/?startpage=2#..{$link->getPageLink('attachment', true,
NULL, "id_attachment={$attachment.id_attachment}")|escape:'html':'UTF-8'}"
width='1024' height='724' allowfullscreen webkitallowfullscreen></iframe>
i can see only second page.

Why?
Thaknks



2015-03-16 15:07 GMT+01:00 Friedrich <notifications@github.com>:

**Comment by kossebau** [comment]
Hi vgianni80, to help us tracking problems, please do not reuse an issue that is about an unrelated problem. I created a new issue #126 for you, let's use that for your problem.
