### ISSUE TITLE
Rackspace URLs don't work

### ISSUE THREAD

**Issue by rmontgomery** [kogmbh/ViewerJS#50]
Using a Rackspace URL, ViewerJS will not load the resource. Rackspace resource URLs are structured as https://[key].ssl.cf2.rackcdn.com/[filename]_[ext]-[id].

Could the lack of the .[ext] in the URL be throwing off ViewerJS?

**Comment by kossebau** [comment]
Yes, the lack of .[ext] at the end of the path threw off ViewerJS.

Today ViewerJS 0.5.5 got released, and it features an initial HEAD request to learn about the content type. Additionally the type can be set by passing an argument to ViewerJS itself, e.g. like `/ViewerJS/index.html?type=pdf#https://[key].ssl.cf2.rackcdn.com/[filename]_[ext]-[id]`.
This should solve the issue, thus closing it now.
