### ISSUE TITLE
Not loading document 

### ISSUE THREAD

**Issue by LohithAnand** [kogmbh/ViewerJS#54]
Hi i am using viewer.js for providing preview option of odp file in my web app. Locally when i tested it was working fine and still works fine (LAMP) ubuntu. But in one of our live server(apache2) the document does not load.

Javascript console shows :
WARNING: refreshOdf called but ODF was not DONE.           webodf.js (line 44)
will be back later...                                                                   webodf.js (line 44)

will be back later..  will be logged every second

**Comment by kossebau** [comment]
Thanks for telling how your problem was resolved. Opened as bug https://github.com/kogmbh/WebODF/issues/858 for WebODF, so closing here.
