### ISSUE TITLE
set default zoom for pdf

### ISSUE THREAD

**Issue by bcbirkhauser** [kogmbh/ViewerJS#58]
Is there a way to set the default zoom for the pdf?  I've tried adding pdf open params to the url, but that has no effect.  I need to set the default zoom to be page-width.

**Comment by kossebau** [comment]
Today ViewerJS 0..5.5 got releaesed, and it comes with https://github.com/kogmbh/WebODF/pull/859 integrated, which picked up the proposal given above by @vandenoever .

So one can now control the initial zoom by passing a zoom argument to ViewerJS, e.g. like `/ViewerJS/index.html?zoom=page-width#pages.pdf`.

Thus closing this issue now.
