### ISSUE TITLE
AJAX load a PDF into a DIV

### ISSUE THREAD

**Issue by isarmstrong** [kogmbh/ViewerJS#70]
Instead of using iFrames to view PDF content, I'd love to use a scrollable DIV. As far as I can tell, the scripts you use would support this but it wold take a lot of modification. Is this something you've played around with? Or am I asking for a unicorn for Christmas again?

**Comment by kossebau** [comment]
Given this request for a unicorn sadly had to be rejected given the focus/mission of this project, closing it also now.
