### ISSUE TITLE
pdf.js latest version

### ISSUE THREAD

**Issue by haydeny** [kogmbh/ViewerJS#90]
In my brief effort to fix a blank document issue with the current ViewerJS source I tried to update the pdf.js and pdf_worker files in the VJS folder to the latest Mozilla files (changing pdf.js from 0.8 to 1.0).

This didn't work as I had hoped as all PDF's stopped displaying.  I'm assuming that as PDF.js matures, display issues and other bugs get ironed out? It makes sense to me that ViewerJS should leverage those updates too?

Or perhaps I'm doing it wrong?  Are there other files I should be updating/amending too?

**Comment by kossebau** [comment]
To update the version of pd.js used, change the commit id here:
https://github.com/kogmbh/ViewerJS/blob/master/CMakeLists.txt#L84

Then build a new ViewerJS following the instructions in [README.md](https://github.com/kogmbh/ViewerJS/blob/master/README.md)

End of this January a new ViewerJS release is planned, which should also come with the latest version of pdf.js
