### ISSUE TITLE
Access pdf outside webserver path

### ISSUE THREAD

**Issue by colomailbe** [kogmbh/ViewerJS#91]
Is it possible to use ViewerJS to access pdf files outside the webserver root ?
i.e. webserver root: /var/www/localhost/htdocs/
pdf files: /var/www/localhost/pdf/storage/

It's to avoid direct download of the pdf (and yes after, I'll still have to disable download button inside the viewer :-)

Thanks!

**Comment by kossebau** [comment]
The initial issue had been already dealt with (no files outside webserver root can be asked for) and thus should have been closed already.

Just it happened that another issue has hijacked this issue then ;) And for that it can be told that ViewerJS 0.5.5 got released today, which features an initial HEAD request to learn about the content type, and also as fallback dropping the arguments from the passed document url, as surely also done in @thenikso's custom logic for `PluginLoader.js`. Additionally the type can be set by passing an argument to ViewerJS itself, e.g. like `/ViewerJS/index.html?type=pdf#/test/pdf/demodoc.pdf?foo=bar`.
These approaches should enable to solve that second problem, and the CORS problem is also outside of ViewerJS's responsibility. So closing this issue now.

**Comment by colomailbe** [comment]
Hi Friedrich,
Maybe my bad, I was dealing with a specific problem at that time but went on other things afterward :-)Anyway thanks for the update! and indeed no problem to close it...
H
