### ISSUE TITLE
Access domain files from subdomain

### ISSUE THREAD

**Issue by MoMannn** [kogmbh/ViewerJS#97]
I am using the viewer on a subdomain and I try to access pdfs that are located at the main domain but with path: /ViewerJS/#../ I can only access the subdomains main folder I cannot access upwards. Since this is still the same server I think there should be a way to access the domain folders aswell.

**Comment by kossebau** [comment]
To reference documents for ViewerJS on the same server (so without using a full url incl. protocol) they have to be in or below the toplevel folder that is served by the server for the domain that ViewerJS is also served for. Means, the document also needs to be accessible directly from the very same webserver which serves ViewerJS. If you cannot create such an url, than it is also not possible to show this document with ViewerJS.
Instead you will need to pass the full url to that document, including protocol and domain, to ViewerJS, e.g. `/ViewerJS#http://domainwithfile.example/file.pdf`
Hope this helps you, thus closing this issue. If not, please reopen the issue and tell which point needs to be better explained still.
